### ISSUE TITLE
External endpoint failure not retrieved for openedition

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/svp-harvester#274]
Task exception was never retrieved :
future: <Task finished name='Task-61406' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:books/psorbonne&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:books/psorbonne&metadataPrefix=qdc with code 502')>
Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:books/psorbonne&metadataPrefix=qdc with code 502

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:books/psorbonne&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:books/psorbonne&metadataPrefix=qdc with code 502

**Comment by jdp1ps** [comment]
Task exception was never retrieved
future: <Task finished name='Task-120219' coro=<IdrefHarvester._query_publication_from_science_plus_endpoint() done, defined at /home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/idref_harvester.py:250> exception=ExternalEndpointFailure('Cant resolve URI : https://scienceplus.abes.fr/sparql?query=define+sql%3Adescribe-mode+%22CBD%22++DESCRIBE+%3Chttp%3A%2F%2Fhub.abes.fr%2Fcairn%2Fperiodical%2Farss%2F1995%2Fissue_arssp1995106n1%2FD33D8AA0C95C4AF4E053120B220A0FF2%2Fw%3E&output=application%2Frdf%2Bxml with error Cannot connect to host scienceplus.abes.fr:443 ssl:default [Connection timed out]')>
Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "uvloop/loop.pyx", line 2039, in create_connection
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/resolver_http_client.py", line 23, in get
    async with session.get(document_url) as resp:
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host scienceplus.abes.fr:443 ssl:default [Connection timed out]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/idref_harvester.py", line 272, in _query_publication_from_science_plus_endpoint
    pub = await client.fetch(query_uri, output_format="xml")
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/rdf_resolver.py", line 23, in fetch
    response_text = await self.http_client.get(document_uri)
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/idref/resolver_http_client.py", line 31, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Cant resolve URI : https://scienceplus.abes.fr/sparql?query=define+sql%3Adescribe-mode+%22CBD%22++DESCRIBE+%3Chttp%3A%2F%2Fhub.abes.fr%2Fcairn%2Fperiodical%2Farss%2F1995%2Fissue_arssp1995106n1%2FD33D8AA0C95C4AF4E053120B220A0FF2%2Fw%3E&output=application%2Frdf%2Bxml with error Cannot connect to host scienceplus.abes.fr:443 ssl:default [Connection timed out]

**Comment by jdp1ps** [comment]
```
Task exception was never retrieved
future: <Task finished name='Task-262218' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/634&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/634&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/634&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/634&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/634&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262263' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:eps/8870&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:eps/8870&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:eps/8870&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:eps/8870&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:eps/8870&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262190' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/14399&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/14399&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/14399&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/14399&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/14399&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262266' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1348&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1348&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1348&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1348&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1348&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262253' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1383&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1383&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1383&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1383&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1383&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262225' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/13683&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/13683&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/13683&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/13683&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:echogeo/13683&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262217' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/6695&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/6695&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/6695&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/6695&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/6695&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262268' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/4552&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/4552&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/4552&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/4552&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/4552&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262264' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/349&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/349&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/349&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/349&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/349&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262207' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/27532&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/27532&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/27532&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/27532&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/27532&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262209' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/578&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/578&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/578&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/578&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/578&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262260' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1139&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1139&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1139&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1139&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1139&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262208' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1124&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1124&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1124&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1124&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1124&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262265' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/32555&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/32555&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/32555&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/32555&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:cybergeo/32555&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262254' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:tem/383&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:tem/383&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:tem/383&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:tem/383&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:tem/383&metadataPrefix=qdc with code 504
Task exception was never retrieved
future: <Task finished name='Task-262246' coro=<IdrefHarvester._query_publication_from_openedition_endpoint() done, defined at /code/app/harvesters/idref/idref_harvester.py:179> exception=ExternalEndpointFailure('Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1424&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1424&metadataPrefix=qdc with code 504')>
Traceback (most recent call last):
  File "/code/app/harvesters/idref/resolver_http_client.py", line 26, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1424&metadataPrefix=qdc with code 504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/app/harvesters/idref/idref_harvester.py", line 193, in _query_publication_from_openedition_endpoint
    pub = await client.fetch(uri)
  File "/code/app/harvesters/idref/open_edition_resolver.py", line 46, in fetch
    response_text = await self.http_client.get(document_url)
  File "/code/app/harvesters/idref/resolver_http_client.py", line 35, in get
    raise ExternalEndpointFailure(
app.harvesters.exceptions.external_endpoint_failure.ExternalEndpointFailure: Error while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1424&metadataPrefix=qdc with error Error code while resolving URI : http://oai.openedition.org/?verb=GetRecord&identifier=oai:revues.org:strates/1424&metadataPrefix=qdc with code 504

```

**Comment by jdp1ps** [comment]
https://stackoverflow.com/questions/68465782/asyncio-wait-handling-exception-sometimes-fails
