### ISSUE TITLE
Persee contributor void name

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/svp-harvester#275]
future: <Task finished name='idref_harvester_retrieval_40' coro=<AbstractHarvester.run() done, defined at /PycharmProjects/svp-harvester/app/harvesters/abstract_harvester.py:90> exception=AssertionError('Unique identifier http://data.persee.fr/authority/#Person violation for contributor cannot occur twice during concept creation : (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class \'asyncpg.exceptions.NotNullViolationError\'>: null value in column "name" of relation "contributors" violates not-null constraint\nDETAIL:  Failing row contains (6050, persee, http://data.persee.fr/authority/#Person, null, {}).\n[SQL: INSERT INTO contributors (source, source_identifier, name, name_variants) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR[]) RETURNING contributors.id]\n[parameters: (\'persee\', rdflib.term.URIRef(\'http://data.persee.fr/authority/#Person\'), None, [])]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)')>

AssertionError: Unique identifier http://data.persee.fr/authority/#Person violation for contributor cannot occur twice during concept creation : (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "name" of relation "contributors" violates not-null constraint

**Comment by jdp1ps** [comment]
For idref : 027016927
```
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "name" of relation "contributors" violates not-null constraint
DETAIL:  Failing row contains (10876, persee, http://data.persee.fr/authority/#Person, null, {}).
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/abstract_harvester.py", line 123, in run
    ] = await self._handle_converted_result(
  File "/home/joachim/PycharmProjects/svp-harvester/app/harvesters/abstract_harvester.py", line 190, in _handle_converted_result
    reference_event = await references_recorder.register_creation(
  File "/home/joachim/PycharmProjects/svp-harvester/app/db/references/references_recorder.py", line 29, in register_creation
    await self._create_reference(new_ref)
  File "/home/joachim/PycharmProjects/svp-harvester/app/db/references/references_recorder.py", line 130, in _create_reference
    async with session.begin():
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 1818, in __aexit__
    await greenlet_spawn(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 146, in __exit__
    with util.safe_reraise():
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 144, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4314, in _flush
    with util.safe_reraise():
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 585, in execute
    self._adapt_connection.await_(
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 564, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/joachim/PycharmProjects/svp-harvester/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 802, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "name" of relation "contributors" violates not-null constraint
DETAIL:  Failing row contains (10876, persee, http://data.persee.fr/authority/#Person, null, {}).
[SQL: INSERT INTO contributors (source, source_identifier, name, name_variants) VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::VARCHAR[]) RETURNING contributors.id]
[parameters: ('persee', 'http://data.persee.fr/authority/#Person', None, [])]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```
