### ISSUE TITLE
Docker container crashes : No module named 'graphviz'

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/svp-harvester#310]
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/app/main.py", line 5, in <module>
    from app.svp_harvester import SvpHarvester
  File "/code/app/svp_harvester.py", line 10, in <module>
    from app.amqp.amqp_interface import AMQPInterface
  File "/code/app/amqp/amqp_interface.py", line 6, in <module>
    from app.amqp.amqp_message_processor import AMQPMessageProcessor
  File "/code/app/amqp/amqp_message_processor.py", line 13, in <module>
    from app.services.retrieval.retrieval_service import RetrievalService
  File "/code/app/services/retrieval/retrieval_service.py", line 18, in <module>
    from app.harvesters.abstract_harvester import AbstractHarvester
  File "/code/app/harvesters/abstract_harvester.py", line 16, in <module>
    from app.harvesters.abstract_references_converter import AbstractReferencesConverter
  File "/code/app/harvesters/abstract_references_converter.py", line 20, in <module>
    from app.services.concepts.concept_factory import ConceptFactory
  File "/code/app/services/concepts/concept_factory.py", line 6, in <module>
    from app.services.concepts.idref_concept_solver import IdRefConceptSolver
  File "/code/app/services/concepts/idref_concept_solver.py", line 9, in <module>
    from app.services.concepts.concept_solver_rdf import ConceptSolverRdf
  File "/code/app/services/concepts/concept_solver_rdf.py", line 2, in <module>
    from graphviz import Graph
ModuleNotFoundError: No module named 'graphviz'

**Comment by jdp1ps** [comment]
@Paldana99 @E-Bara How did this dependency appear ? How did it cross the CI-CD pipeline to reach K8S deployment ? :thinking:
