### ISSUE TITLE
Idref result without tile

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/svp-harvester#369]
https://scienceplus.abes.fr/sparql?query=define%20sql%3Adescribe-mode%20%22CBD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fhub.abes.fr%2Fcup%2Fperiodical%2Faqy%2F2002%2Fvolume_76%2Fissue_291%2F101017s0003598x00089894AF24EABC6EF14AF5E053120B220A632E%2Fw%3E&output=application%2Frdf%2Bxml

With 

Schlanger,Nathan, 084265019,0000-0002-2029-4929,nathan-schlanger

**Comment by jdp1ps** [comment]
```
Task exception was never retrieved
future: <Task finished name='idref_harvester_retrieval_4519' coro=<AbstractHarvester.run() done, defined at /code/app/harvesters/abstract_harvester.py:90> exception=AssertionError('Validation failed in method SciencePlusReferencesConverter.convert for reference: http://hub.abes.fr/cup/periodical/flm/2010/volume_662/issue_2010/101017s0022112010004052AF1F9BC58836239FE053120B220A6696/w. titles should be set on reference')>
Traceback (most recent call last):
  File "/code/app/harvesters/abstract_harvester.py", line 120, in run
    await self.converter.convert(raw_data=raw_data, new_ref=new_ref)
  File "/code/app/harvesters/idref/idref_references_converter.py", line 45, in convert
    await self.secondary_converter.convert(raw_data=raw_data, new_ref=new_ref)
  File "/code/app/harvesters/abstract_references_converter.py", line 146, in wrapper
    assert False, (
AssertionError: Validation failed in method SciencePlusReferencesConverter.convert for reference: http://hub.abes.fr/cup/periodical/flm/2010/volume_662/issue_2010/101017s0022112010004052AF1F9BC58836239FE053120B220A6696/w. titles should be set on reference
```
